declare type EnumGender = 'M' | 'F'
declare type EnumJobRisk = 'NonRisk' | 'HeavyRisk' | 'HighRisk'
declare type EnumAgency = 'SKT' | 'KT' | 'LGU' | 'SKTA' | 'KTA' | 'LGUA'
declare type EnumCompany = 'IN' | 'OUT'
declare type EnumNotification = 'SMS' | 'EMAIL' | 'PUSH' | 'SLACK'
declare type EnumAnalysis = 'NEW' | 'OLD'
declare type EnumContent = 'EVENT' | 'NOTICE' | 'INSURER'
declare type EnumDelegate = 'INC' | 'DEC'
declare type EnumPolicy = 'KCREDIT' | 'BODOC'
declare type EnumInvoice = 'DISEASE' | 'WOUND'
declare type EnumSend =
  | 'INIT'
  | 'GENERATING'
  | 'DOCUMENT_SUCCESS'
  | 'DOCUMENT_FAIL'
  | 'FAX_SENDING'
  | 'FAX_SUCCESS'
  | 'EMAIL_SENDING'
  | 'EMAIL_SUCCESS'
declare type EnumResult = 'SUCCESS' | 'FAIL'
declare type EnumTerminator = 'IN' | 'OUT' | 'MISS'
declare type EnumOptionType = 'ALL' | 'RESIGN' | 'WORK' | 'MANUAL' | 'REASSIGN'
declare type EnumAdminManageType = 'OTP' | 'PASSWORD'
declare type EnumPublishStatusType =
  | 'ALL'
  | 'COMPLETE'
  | 'INCOMPLETE'
  | 'MANUAL'
declare type EnumClaim = 'ME' | 'FAMILY'
declare type EnumTextType =
  | 'MAIN_TITLE'
  | 'MAIN_DESC'
  | 'LISTS'
  | 'DRAWBACK_TITLE'
  | 'DRAWBACK_DESC'
  | 'LINK'
declare type EnumCustomer = 'TEMP' | 'CUSTOMER'
declare type EnumNotice =
  | 'UPDATE'
  | 'EMERGENCY'
  | 'ISSUE'
  | 'GUIDE'
  | 'FAILURE'
  | 'FEED'
declare type EnumEvent = 'REVIEW' | 'MORE' | 'JOIN'
declare type EnumDateTarget = 'START' | 'END'
declare type EnumStatus = 'WIP' | 'FIN' | 'OPN'
declare type EnumPushCategory =
  | 'NOTICE'
  | 'EVENT'
  | 'NORMAL'
  | 'PUBLIISH'
  | 'CALC'
  | 'FEED'
declare type EnumAppSend = 'NOW' | 'RESERVED' | 'REFEAT'
declare type EnumPush = 'NONE' | 'IMMY' | 'REZ' | 'REZREPS'
declare type EnumInterval = 'DAYS' | 'WEEKS'
